### PR TITLE
Use `finally` in `run_bulk_job` and catch StopIteration

### PR DESCRIPTION
**Pull request by jakirkham**
Fixes https://github.com/pygridtools/drmaa-python/issues/54

Previously this code was using `except` and `else` to do the same handling. Better to just use `finally` in this case, which is what we do here.

Also squash a `StopIteration` exception that is not otherwise caught. Not totally sure how it was getting raised in the first place, but catching it avoids a `DeprecationWarning` and has no real other effect for the code.

cc @pitrou

### CODE REVIEW

**Comment by jakirkham** [comment]
Failing because Travis CI switched to Ubuntu Trusty and the CI install was designed around Ubuntu Precise. PR ( https://github.com/pygridtools/drmaa-python/pull/63 ) configures Travis CI to use Ubuntu Precise anyways, which fixes the issue. Will rebase after that is merged.

**Comment by jakirkham** [comment]
@desilinguist, could you please take a look at these two PRs?

**Comment by desilinguist** [comment]
Sorry for the delay. I merged #63.

**Comment by jakirkham** [comment]
No worries. Thanks for taking a look.

Merged `master` into this PR. Expect it should pass. Any thoughts on it?

**Comment by desilinguist** [comment]
Looks good to me 👍.

**Comment by jakirkham** [comment]
Thanks. Looks like it's good to go.

**Pull request merged**
